[datasets]


#########
# IGANG #
#########

    [datasets.igang_videregaaende]
    team = "utd-vg"
    bucket = "vgu"
    path_glob = "vgu/klargjorte-data/nudb/igang-videregaaende_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"
    variables = [
        # pers
        "snr",
        "fnr",

        # data
        "utd_datakilde",
        "nudb_dataset_id",

        # tid
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_skoleaar_start",

        # fag
        "nus2000",
        "utd_klassetrinn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "utd_viderutd_nettbasert",
        "utd_utdanningstype",
        "vg_rettstype_inntak",

        # skole
        "orgnrbed",
        "orgnr_foretak",
        "utd_skolekom",

        # gro
        "gro_elevstatus",
        "gro_skolenr_inn",
        "gro_programomraade",

        # vg
        "vg_antall_aarstimer_elevkurs",
        "vg_kursprosent",
        "vg_antall_fag_elevkurs",
        "vg_kontraktstype",
        "vg_ernylaerling",
        "vg_erhovedaktivitet",
        "vg_utdprogram",
        "vg_yrkes_og_studiekompetanse",


        # uh
        "utd_utveksling",

        # derived
        "pers_foedselsdato",
        "pers_kjoenn",
        "snr_mrk",  # We dont demand this delivered, as we will reproduce anyway, but vg has decided to deliver it
    ]

        [datasets.igang_videregaaende.thresholds_empty]
            fnr = 0.0


    [datasets.igang_fagskole]
        team = "utd-uhfagskole"
        bucket = "fagskole"
        path_glob = "fagskoler/klargjorte-data/nudb/igang-fagskole_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",

            # tid
            "utd_aktivitet_start",
            "utd_aktivitet_start_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "utd_utdanningstype",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",

            # fa
            "fa_erhovedaktivitet",
            "fa_institusjon_id",
            "fa_studiestednr_inn",
            "fa_utveksl_varighet_dager",
            "fa_tilbudskode",
            "fa_tilbudsnavn",
            "fa_nettbasert_antall_samledager_tilbud",

            # fuh
            "fuh_opptaksgrunnlag",

            # uh
            "utd_utveksling",

            # land
            "fuh_utvekslingsland",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

    [datasets.igang_fagskole.thresholds_empty]
        fnr = 0.0


    [datasets.igang_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = "uvh/klargjorte-data/nudb/igang-hoeyereutdanning_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"

        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",

            # tid
            "utd_aktivitet_start",
            "utd_aktivitet_start_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "utd_utdanningstype",
            "uh_studieprogram",
            "uh_studienivaa",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",
            "uh_institusjon_id",

            # fuh
            "fuh_opptaksgrunnlag",

            # uh
            "utd_utveksling",
            "uh_campus_sted",
            "uh_campus_kommune",
            "uh_utvekslingsavtale",
            "uh_studierett",
            "uh_programprosent",
            "uh_erpermisjon",
            "uh_studieprogresjon_hoest",
            "uh_utdplan",
            "uh_erhovedaktivitet",
            "uh_undervisningsspraak",

            # land
            "utd_studieland",
            "fuh_utvekslingsland",
            "uh_studgrunnlagsland",
            "uh_statsborgerskap_inn",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

        [datasets.igang_hoeyereutdanning.thresholds_empty]
            fnr = 0.0

############
# AVSLUTTA #
############

    [datasets.avslutta_grunnskole]
    team = "utd-bhgskole"
    bucket = "kargrs"
    path_glob = "kargrs/klargjorte-data/avslutta-grunnskole_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",
            "utd_fullfoertkode",

            # tid
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_viderutd_nettbasert",
            "utd_utdanningstype",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "gro_skolenavn_inn",
            "utd_skolekom",

            # gr
            "gr_grunnskolepoeng",

            # gro
            "gro_elevstatus",
            "gro_skolenr_inn",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_programomraade",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

        [datasets.avslutta_grunnskole.thresholds_empty]
            fnr = 0.0



    [datasets.avslutta_videregaaende]
        team = "utd-vg"
        bucket = "vgu"
        path_glob = "vgu/klargjorte-data/nudb/avslutta-videregaaende_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"

        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",
            "nudb_dataset_id",
            "utd_fullfoertkode",

            # tid
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_viderutd_nettbasert",
            "utd_utdanningstype",
            "vg_rettstype_inntak",
            "vg_bevistype",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",

            # gro
            "gro_elevstatus",
            "gro_skolenr_inn",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_programomraade",

            # vg
            "vg_fullfoertkode_detaljert",
            "vg_kursprosent",
            "vg_karakterpoeng",
            "vg_ervedtak_saer_spraak",
            "vg_proevenr",
            "vg_proeve_dato",
            "vg_proevestatus",
            "vg_resultat_teori",
            "vg_resultat_praktisk_proeve",
            "vg_proevekandtype",
            "vg_erhovedaktivitet",
            "vg_utdprogram",
            "vg_yrkes_og_studiekompetanse",  # old_name: taf

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
            "snr_mrk",  # We dont demand this delivered, as we will reproduce anyway, but vg has decided to deliver it
        ]
        [datasets.avslutta_videregaaende.thresholds_empty]
            fnr = 0.0

    [datasets.avslutta_fagskole]
        team = "utd-uhfagskole"
        bucket = "fagskole"
        path_glob = "fagskoler/klargjorte-data/nudb/avslutta-fagskole_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",
            "utd_fullfoertkode",

            # tid
            "utd_aktivitet_slutt",
            "utd_aktivitet_slutt_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "utd_utdanningstype",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",

            # fa
            "fa_institusjon_id",
            "fa_karakter",
            "fa_studiestednr_inn",
            "fa_tilbudskode",
            "fa_tilbudsnavn",
            "fa_nettbasert_antall_samledager_tilbud",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

    [datasets.avslutta_fagskole.thresholds_empty]
            fnr = 0.0


    [datasets.avslutta_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = "uvh/klargjorte-data/nudb/avslutta-hoeyereutdanning_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"

        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",
            "utd_fullfoertkode",

            # tid
            "utd_aktivitet_slutt",
            "utd_aktivitet_slutt_inn",
            "utd_skoleaar_start",

            # fag
            "nus2000",
            "utd_klassetrinn",
            #"utd_aktivitetsnivaa_heltid_deltid",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "utd_utdanningstype",
            "uh_studieprogram",
            "uh_studieprogram_navn",
            "uh_studienivaa",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",
            "uh_institusjon_id",

            # uh
            #"uh_campus_sted",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            #"uh_campus_kommune",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            "uh_studiepoeng_grad",
            #"uh_fakultet",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            "uh_ervitnemaalsgivende",

            # land
            "utd_studieland",
            "uh_statsborgerskap_inn",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

        [datasets.avslutta_hoeyereutdanning.thresholds_empty]
            fnr = 0.0



###########
# EKSAMEN #
###########



    [datasets.eksamen_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = "uvh/klargjorte-data/nudb/eksamen-hoeyereutdanning_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",
            "fnr",

            # data
            "utd_datakilde",

            # tid
            "utd_skoleaar_start",
            "uh_eksamen_dato",

            # fag
            "nus2000",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "utd_utdanningstype",
            "uh_termin_rapportert",
            "uh_studieprogram",
            "uh_studieprogram_navn",
            "uh_eksamen_karakter",
            "uh_emnekode",
            "uh_studienivaa",
            "uh_emnenavn",

            # skole
            "orgnrbed",
            "orgnr_foretak",
            "utd_skolekom",
            "uh_institusjon_id",

            # uh
            "uh_fullfoertkode_inn",  # Kommer i 2026?
            "uh_campus_sted",  # Kommer i 2026?
            "uh_campus_kommune",  # Kommer i 2026?
            "uh_eksamen_studpoeng",
            "uh_eksamen_ergjentak",
            "uh_programprosent",
            "uh_ereksamenrett",

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",
        ]

    [datasets.eksamen_hoeyereutdanning.thresholds_empty]
            fnr = 0.0
