[datasets]

    [datasets.igang]
        team = "utd-nudb"
        bucket = "utdanning"
        path_glob = "nudb-data/klargjorte-data/igang/igang_p[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",  # old_name: snr
            "fnr",

            # data
            "utd_datakilde",  # old_name: kilde
            "nudb_dataset_id",

            # tid
            "utd_aktivitet_start",  # old_name: startd
            "utd_aktivitet_start_inn",  # old_name: kurs_start_orig
            "utd_skoleaar_start",  # old_name: aargang

            # fag
            "nus2000",
            "utd_klassetrinn",  # old_name: kltrinn2000
            "utd_aktivitetsnivaa_heltid_deltid",  # old_name: heldel
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "fuh_nett_eller_stedbasert",  # old_name: organisering
            "utd_utdanningstype",  # old_name: utd
            "vg_rettstype_inntak",  # old_name: rett
            "uh_studieprogram",
            "uh_studienivaa",  # old_name: studieniva

            # skole
            "orgnrbed",
            "orgnr_foretak",  # old_name: orgnr
            "utd_skolekom",  # old_name: skolekom
            "uh_institusjon_id",  # old_name: hskode
            "gro_skolenavn_inn",  # old_name: skolenavn

            # gro
            "gro_elevstatus",  # old_name: elevstatus
            "gro_skolenr_inn",  # old_name: fskolenr
            "gro_programomraade",  # Gamle fkurskod?

            # vg
            "vg_antall_aarstimer_elevkurs",  # old_name: aartimer
            "vg_kursprosent",  # old_name: delpros
            "vg_antall_fag_elevkurs",
            "vg_kontraktstype",  # old_name: kontraktstype
            "vg_yrkes_og_studiekompetanse",  # old_name: taf
            "vg_ernylaerling",  # old_name: nylaerl
            "vg_erhovedaktivitet",
            "vg_utdprogram",

            # fa
            "fa_erhovedaktivitet",
            "fa_institusjon_id",
            "fa_studiestednr_inn",
            "fa_utveksl_varighet_dager",
            "fa_tilbudskode",
            "fa_tilbudsnavn",
            "fa_nettbasert_antall_samledager_tilbud",

            # fuh
            "fuh_opptaksgrunnlag",  # old_name: realkomp

            # uh
            "utd_utveksling",  # old_name: utveks
            "uh_campus_sted",  # old_name: campus_sted
            "uh_campus_kommune",  # old_name: campus_kom
            "uh_utvekslingsavtale",  # old_name: utveksavtale
            "uh_studierett",  # old_name: studrett
            "uh_programprosent",
            #"uh_erpermisjon",  # old_name: permisjon  # Temporary decision is that this should be removed before sharing, for now
            "uh_studieprogresjon_hoest",  # old_name: studieprogresjon_h
            "uh_utdplan",  # old_name: utdplan
            "uh_erhovedaktivitet",
            "uh_undervisningsspraak",  # undervisningssprak

            # land
            "utd_studieland",  # old_name: studieland
            "fuh_utvekslingsland",  # old_name: utveksland
            "uh_studgrunnlagsland",  # old_name: studgrland
            "uh_statsborgerskap_inn",  # old_name: statb_meldt

            # derived
            "pers_foedselsdato",
            "pers_kjoenn",  # old_name: kjoenn
            "snr_mrk",  # See Jira NUD-482 for decision to include
        ]

    [datasets.igang.dataset_specific_renames]
            ftype = "vg_kontraktstype"
            ftypef = "vg_kontraktstype"

    [datasets.igang.thresholds_empty]
            fnr = 0.0  # Vi vil ha fnr på alle takk.
            snr = 4.0
            utd_aktivitet_start = 0.0
            utd_skoleaar_start = 0.0
            nus2000 = 0.0
            utd_skolekom = 0.0


            # Measured from igang build and rounded up slightly
            pers_kjoenn = 1.1
            utd_datakilde = 40.0
            pers_foedselsdato = 0.5
            utd_aktivitet_start_inn = 50.0
            orgnrbed = 30.0
            orgnr_foretak = 17.0
            utd_klassetrinn = 0.1
            utd_aktivitetsnivaa_heltid_deltid = 0.0
            utd_viderutd_nettbasert = 50.0
            fuh_nett_eller_stedbasert = 90.0
            utd_utdanningstype = 20.0
            utd_utveksling = 99.5
            gro_elevstatus = 85.0
            gro_programomraade = 98.0
            vg_antall_aarstimer_elevkurs = 85.0
            vg_kursprosent = 75.0
            vg_kontraktstype = 98.0
            vg_yrkes_og_studiekompetanse = 99.9
            vg_rettstype_inntak = 75.0
            vg_utdprogram = 60.0
            uh_institusjon_id = 70.0
            #uh_univ_eller_hoegskole = 75.0
            fuh_opptaksgrunnlag = 80.0
            uh_utvekslingsavtale = 99.9
            uh_studierett = 90.0
            uh_studieprogresjon_hoest = 90.0
            uh_utdplan = 90.0
            #uh_erutland = 99.0
            utd_studieland = 99.0
            fuh_utvekslingsland = 99.9
            uh_studgrunnlagsland = 99.9
            uh_statsborgerskap_inn = 98.0


    [datasets.eksamen]
        team = "utd-nudb"
        bucket = "utdanning"
        path_glob = "nudb-data/klargjorte-data/eksamen/eksamen_p[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",  # old_name: snr
            "fnr",

            # data
            "utd_datakilde",  # old_name: kilde
            "nudb_dataset_id",

            # tid
            "utd_skoleaar_start",  # old_name: skoleaar_start
            "uh_eksamen_dato",

            # fag
            "nus2000",  # Personvariabler ?
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "fuh_nett_eller_stedbasert",  # old_name: organisering
            "utd_utdanningstype",  # old_name: utd
            "uh_termin_rapportert",  # old_name: termrapp
            "uh_studieprogram",  # old_name: studprog
            "uh_studieprogram_navn",  # old_name: studprog_navn
            "uh_eksamen_karakter",  # old_name: karakter_eks
            "uh_emnekode",  # old_name: emnekode
            "uh_studienivaa",  # old_name: studnivaa
            "uh_emnenavn",  # old_name: emnekode_navn

            # skole
            "orgnrbed",
            "orgnr_foretak",  # old_name: orgnr
            "utd_skolekom",  # old_name: skolekom
            "uh_institusjon_id",  # old_name: hskode

            # uh
            "uh_fullfoertkode_inn",
            "uh_campus_sted",
            "uh_campus_kommune",
            "uh_eksamen_studpoeng",  # old_name: studpoeng_eks
            "uh_eksamen_ergjentak",  # old_name: gjentak
            "uh_antall_deleksamener",  # old_name: antall_deleks
            "uh_antall_deleksamener_bestatt",  # old_name: antall_deleks_bestaatt
            "uh_programprosent",
            "uh_ereksamenrett",  # old_name: studrett, uh_studierett

            # derived
            "pers_foedselsdato",  # old_name: fodt_dato
            "pers_kjoenn",  # old_name: kjoenn
            "snr_mrk",  # See Jira NUD-482 for decision to include
        ]
    [datasets.eksamen.min_values]
        nus2000 = "600000"  # Triple-checked with AM

    [datasets.eksamen.max_values]
        nus2000 = "799999"

    [datasets.eksamen.thresholds_empty]
            #utd_hendelse_id = 0.0
            fnr = 0.0  # Dette er ganske lavt ass...
            snr = 4.0
            pers_kjoenn = 2.6
            pers_foedselsdato = 0.3
            nus2000 = 0.0
            utd_datakilde = 0.0
            orgnrbed = 9.0
            orgnr_foretak = 0.5
            utd_skolekom = 0.05
            uh_institusjon_id = 0.01
            uh_eksamen_dato = 0.0

            # Målte verdier
            utd_viderutd_nettbasert = 0.001
            uh_eksamen_studpoeng = 0.0
            uh_eksamen_ergjentak = 0.0
            utd_utdanningstype = 0.04
            utd_skoleaar_start = 0.0
            uh_termin_rapportert = 35.0  # Ny variabel fom 2014, utfylling bør gå opp
            uh_studieprogram = 32.0 # Ny variabel fom 2014, utfylling bør gå opp
            uh_eksamen_karakter = 32.0 # Ny variabel fom 2014, utfylling bør gå opp
            #uh_eksamen_dato_inn = 32.0 # Ny variabel fom 2014, butfylling ør gå opp
            uh_emnekode = 32.0 # Ny variabel fom 2014, utfylling bør gå opp
            fuh_nett_eller_stedbasert = 38.0 # Ny variabel fom 2015, utfylling bør gå opp
            uh_studienivaa = 60.0 # Ny variabel fom 2018, utfylling bør gå opp
            uh_studieprogram_navn = 93.0 # Ny variabel fom 2023, utfylling bør gå opp
            uh_emnenavn = 93.0 # Ny variabel fom 2023, utfylling bør gå opp



[datasets.avslutta]
    team = "utd-nudb"
    bucket = "utdanning"
    path_glob = "nudb-data/klargjorte-data/avslutta/avslutta_p[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_v*[0-9].parquet"
        variables = [
            # pers
            "snr",  # old_name: snr
            "fnr",

            # data
            "utd_datakilde",  # old_name: kilde
            "nudb_dataset_id",
            "utd_fullfoertkode",  # old_name: utfall

            # tid
            "utd_aktivitet_start",  # old_name: kurs_start
            "utd_aktivitet_slutt",  # old_name: kurs_slutt
            "utd_aktivitet_start_inn",  # old_name: kurs_start_orig
            "utd_aktivitet_slutt_inn",  # old_name: kurs_slutt_orig
            "utd_skoleaar_start",  # old_name: aargang

            # fag
            "nus2000",
            "utd_klassetrinn",  # old_name: kltrinn2000
            "utd_aktivitetsnivaa_heltid_deltid",  # old_name: heldel
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "fuh_nett_eller_stedbasert",  # old_name: organisering
            "utd_utdanningstype",  # old_name: utd
            "vg_rettstype_inntak",  # old_name: rett
            "vg_bevistype",  # old_name: doktype
            "uh_studieprogram",  # old_name: studprog
            "uh_studieprogram_navn",
            "uh_studienivaa",  # old_name: studnivaa

            # skole
            "orgnrbed",
            "orgnr_foretak",  # old_name: orgnr
            "gro_skolenavn_inn",
            "utd_skolekom",  # old_name: skolekom
            "uh_institusjon_id",  # old_name: hskode

            # gr
            "gr_grunnskolepoeng",  # old_name: grunnskolepoeng

            # gro
            "gro_elevstatus",  # old_name: elevstatus
            "gro_skolenr_inn",  # old_name: fskolenr
            "gro_fravaer_dager",  # old_name: f_dager
            "gro_fravaer_timer",  # old_name: f_timer
            "gro_programomraade",  # Gamle fkurskod?

            # vg
            "vg_fullfoertkode_detaljert",  # old_name: utfallu
            "vg_kursprosent",  # old_name: delpros
            "vg_karakterpoeng",
            "vg_ervedtak_saer_spraak",  # old_name: fkurskod
            "vg_proevenr",  # old_name: provnr
            "vg_proeve_dato",
            "vg_proevestatus",
            "vg_resultat_teori",
            "vg_resultat_praktisk_proeve",
            "vg_proevekandtype",  # old_name: provekandtype
            "vg_erhovedaktivitet",
            "vg_utdprogram",
            "vg_yrkes_og_studiekompetanse",  # old_name: taf

            # fa
            "fa_institusjon_id",
            "fa_karakter",
            "fa_studiestednr_inn",
            "fa_tilbudskode",
            "fa_tilbudsnavn",
            "fa_nettbasert_antall_samledager_tilbud",

            # uh
            #"uh_campus_sted",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            #"uh_campus_kommune",  # Kan ikke leveres nå, kanskje senere? 2026-05-20
            "uh_studiepoeng_grad",  # old_name: studpoeng_grad
            "uh_erhovedaktivitet",
            #"uh_fakultet",  # old_name: fakultet  # Bør være 6 siffer - Kan ikke leveres nå fra UH, kanskje senere? Beholdes her fordi den har data fra andre kilder 2026-05-20
            "uh_ervitnemaalsgivende",

            # land
            "utd_studieland",  # old_name: studieland
            "uh_statsborgerskap_inn",  # old_name: statb_meldt

            # derived
            "pers_foedselsdato",  # old_name: fodt_dato
            "pers_kjoenn",  # old_name: kjoenn
            "snr_mrk",  # See Jira NUD-482 for decision to include
        ]
        [datasets.avslutta.dataset_specific_renames]
            ftype = "vg_proevekandtype"
            ftypef = "vg_proevekandtype"

        [datasets.avslutta.thresholds_empty]
            fnr = 0.0  # Vi vil ha fnr på alle takk
            snr = 4.0
            nus2000 = 0.0


    [datasets.grunnskolekarakterer]
        team = "utd-nudb"
        bucket = "utdanning"
        path_glob = "nudb-data/klargjorte-data/grunnskolekarakterer/grunnskolekarakterer_p[0-9][0-9][0-9][0-9]_p[0-9][0-9][0-9][0-9]_v*[0-9].parquet"

        variables = [
            # pers
            "snr",  # old_name: snr
            "fnr",

            # tid
            "utd_skoleaar_start",  # old_name: skoleaar_slutt

            # skole
            "orgnr_foretak",  # old_name: orgnr
            "utd_skolekom",  # old_name: skolekom

            # gr
            "gr_med_pub_kargs_kar",

            # gro
            "gro_skolenr_inn",
            "gro_fagkode_vigo",

            # karakter
            "gro_karakter_standpunkt",
            "gro_karakter_skriftlig",
            "gro_karakter_muntlig",
            "gro_karakter_termin1",
            "gro_karakter_termin2",
            "gro_karakter_praktisk_muntlig",

            # derived
            "snr_mrk",  # See Jira NUD-482 for decision to include
        ]

        [datasets.grunnskolekarakterer.thresholds_empty]
            snr = 0.1
            orgnr_foretak = 0.1
            utd_skolekom = 0.05
            gro_fagkode_vigo = 0.0
            gro_karakter_standpunkt = 4.0
            gro_karakter_skriftlig = 93.0
            gro_karakter_muntlig = 96.0
            gro_karakter_termin1 = 15.0
            gro_karakter_termin2 = 99.93
            gro_karakter_praktisk_muntlig = 99.99
