[datasets]

    [datasets.igang]
        variables = [
            "fnr",
            "pers_id",  # old_name: snr
            #"snr_mrk",
            "utd_skoleaar_start",  # old_name: aargang
            "nus2000",
            "utd_klassetrinn",  # old_name: kltrinn2000
            "utd_aktivitetsnivaa_heltid_deltid",  # old_name: heldel
            "utd_aktivitet_start",  # old_name: startd
            # "voksen",
            "uh_realkompetanse",  # old_name: realkomp
            "utd_datakilde",  # old_name: kilde
            "vg_rettstype_inntak",  # old_name: rett
            # "ftype",
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "uh_studierett",  # old_name: studrett
            "utd_utdanningstype",  # old_name: utd
            "utd_skolekom",  # old_name: skolekom
            # "eierf",
            "uh_institusjon_id",  # old_name: hskode
            #"inr",
            "utd_orgnr",  # old_name: orgnr
            "uh_studieland",  # old_name: studieland
            "uh_univ_eller_hogskole",  # old_name: univ
            "utd_aktivitet_start_mrk_kilde",  # old_name: mrk_dl
            "uh_utland",  # old_name: utland
            "vg_kursprosent",  # old_name: delpros
            "vg_antall_aarstimer_elevkurs",  # old_name: aartimer
            "gro_elevstatus",  # old_name: elevstatus
            # "realkompetansevurdert_dato",  # old_name: dato_dokrealkomp
            "bof_orgnr_bed",  # old_name: orgnrbed
            "fa_godkjent_fagskoleutd",  # old_name: fagskoleutd
            "vg_yrkes_og_studiekompetanse",  # old_name: taf
            "utd_utveksling",  # old_name: utveks
            "uh_utvekslingsland",  # old_name: utveksland
            "uh_studgrunnlagsland",  # old_name: studgrland
            "uh_utdplan",  # old_name: utdplan
            # "sn07",
            "pers_kjoenn",  # old_name: kjoenn
            "pers_foedselsdato",
            #"foedselsaar",
            "uh_utvekslingsavtale",  # old_name: utveksavtale
            "uh_studieprogresjon_hoest",  # old_name: studieprogresjon_h
            "uh_statsborgerskap_inn",  # old_name: statb_meldt
            "fuh_nett_eller_stedbasert",  # old_name: organisering
            "vg_vedtak_saerskilt_spraak",  # old_name: fkurskod
            "vg_kontraktstype",  # old_name: kontraktstype
            "uh_studieprogram",
    ]
    [datasets.eksamen_uh]
        variables = [
            "fnr",
            "pers_id",  # old_name: snr
            #"snr_mrk",
            #"snr_mrk_freg",
            "pers_kjoenn",  # old_name: kjoenn
            "pers_foedselsdato",  # old_name: fodt_dato
            "nus2000",   # Personvariabler ?
            # "estart",
            # "kstart",
            # "startd",
            # "mrk_dl",  # Tidsvariabler ?
            # "kilde",
            # 'snr_nudb',
            'utd_datakilde',  # old_name: kilde
            'uh_eksamen_studpoeng',  # old_name: studpoeng_eks
            'uh_eksamen_er_gjentak',  # old_name: gjentak
            'utd_skolekom',  # old_name: skolekom
            'uh_antall_deleksamener',  # old_name: antall_deleks
            'uh_antall_deleksamener_bestatt',  # old_name: antall_deleks_bestaatt
            # 'studieprogresjon',
            # 'studieprogresjon_h',
            'uh_termin_rapportert',  # old_name: termrapp
            'uh_eksamen_karakter',  # old_name: karakter_eks
            # 'eavsl',
            'uh_studieprogram',  # old_name: studprog
            'uh_emnekode',  # old_name: emnekode
            'uh_studienivaa',  # old_name: studnivaa
            'uh_studieprogram_navn',  # old_name: studprog_navn
            'uh_emnekode_navn',  # old_name: emnekode_navn
            # 'foedselsdato',
            # 'start_dato',
            # 'slutt_dato',
            # 'start_dato_kilde',
            # 'slutt_dato_kilde',
            'uh_eksamen_dato',
            'uh_eksamen_dato_inn',
            #"kilde_dato",
            'utd_skoleaar_start',  # old_name: skoleaar_start
            'utd_skoleaar_slutt',  # old_name: skoleaar_slutt
            "utd_utdanningstype",  # old_name: utd
            "uh_univ_eller_hogskole", # old_name: univ
            #"heldel",  # Hvordan kan en eksamen "være heltid"? Mellom 2003 og 2012 så er ALLE eksamener "heltid"...
            "utd_orgnr",  # old_name: orgnr
            "bof_orgnr_bed",  # old_name: orgnrbed
            # "eierf",
            # "skolekom",
            # "rett",
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "fuh_nett_eller_stedbasert", # old_name: organisering
            "uh_institusjon_id",  # old_name: hskode
            # "utdplan",
            "uh_studierett",  # old_name: studrett
            # "studgrland",
            # "utland",
            # "utveks",
            # "utveksavtale",
            # "utveksland",
            # "studieland",
            # "statb_meldt",  # UH-variabler?
            # "studieprogresjon_h",
            # "fagskoleutd",
            # "taf",
            # "delpros",
            # "aartimer",
            # "elevstatus",
            # "realkomp",
            # "dato_dokrealkomp",
            # "ftype",
            # "fkurskod",
            # "kontraktstype", ikke relevant??
            # "voksen",
    ]
    [datasets.eksamen_uh.min_values]
        nus2000 = "500000"

    [datasets.eksamen_uh.max_values]
        nus2000 = "799999"

[datasets.avslutta]
        variables = [
            "utd_hendelse_id",
            "fnr",
            "pers_id",  # old_name: snr
            #"snr_mrk",
            "pers_kjoenn",  # old_name: kjoenn
            "utd_datakilde",  # old_name: kilde
            "utd_fullfoertkode",  # old_name: utfall
            "utd_fullfoertkode_inn",  # old_name: utfallu
            # "mrk_grskole", Trengs ikke
            "vg_bevistype",  # old_name: doktype
            "vg_rettstype_inntak",  # old_name: rett
            # "realkompetansevurdert_dato", skal ikke være med?
            "utd_aktivitetsnivaa_heltid_deltid",  # old_name: heldel
            "utd_klassetrinn",  # old_name: kltrinn2000
            "nus2000",
            "utd_viderutd_nettbasert",  # old_name: evufjern
            "fuh_nett_eller_stedbasert",  # old_name: organisering
            "uh_studieprogram",  # old_name: studprog
            "uh_studienivaa",  # old_name: studnivaa
            "utd_utdanningstype",  # old_name: utd
            "gr_grunnskolepoeng",  # old_name: grunnskolepoeng
            "uh_utland",  # old_name: utland
            "uh_studieland",  # old_name: studieland
            "uh_statsborgerskap_inn",  # old_name: statb_meldt
            "bof_orgnr_bed",  # old_name: orgnrbed
            "utd_orgnr",  # old_name: orgnr
            "gro_skolenavn_inn",
            "utd_skolekom",  # old_name: skolekom
            #"eierf",  # Koble på fra BOF isteden for å ligge på filen
            "uh_institusjon_id",  # old_name: hskode
            "uh_univ_eller_hogskole",
            "pers_foedselsdato",  # old_name: fodt_dato
            "utd_aktivitet_slutt_inn",  # old_name: kurs_slutt_orig
            "utd_aktivitet_start",  # old_name: kurs_start
            "utd_aktivitet_slutt",  # old_name: kurs_slutt
            "utd_aktivitet_start_inn",  # old_name: kurs_start_orig
            "uh_studiepoeng_grad",  # old_name: studpoeng_grad
            "uh_studierett",  # old_name: studrett
            "uh_fakultet",  # old_name: fakultet
            "gro_fravaer_timer",  # old_name: f_timer
            "gro_fravaer_dager",  # old_name: f_dager
            # "pedsem", Skal ikke være med fordi den bør utledes fra NUS
            "vg_provenr",  # old_name: provnr
            # "endret_utfall", Hvor kommer den fra? Avslutta?
            # "mrk_dl_bhu", Kommer fra eldre filer
            "utd_skoleaar_start",  # old_name: aargang
            "utd_skoleaar_slutt",
            "fa_godkjent_fagskoleutd",  # old_name: fagskoleutd
            "gro_elevstatus",  # old_name: elevstatus
            "vg_vedtak_saerskilt_spraak",  # old_name: fkurskod
            "vg_kursprosent",  # old_name: delpros
            "vg_programomraade",  # Gamle fkurskod?
            "vg_karakterpoeng",
            "vg_prove_dato",
            "fuh_nett_eller_stedbasert",
            "gro_skolenr_inn",  # old_name: fskolenr
            "vg_provekandtype",  # old_name: provekandtype
            ]


    [datasets.grunnskolekarakterer]
        variables = [
            'pers_id',  # old_name: snr
            #'snr_mrk',
            'utd_orgnr',  # old_name: orgnr
            'utd_skolekom',  # old_name: skolekom
            'fagkode',
            'stp',
            'skr',
            'mun',
            'utd_skoleaar_slutt',  # old_name: skoleaar_slutt
            'termin1',
            'termin2',
            'kar_annen',
        ]

        [datasets.grunnskolekarakterer.thresholds_empty]
            snr = 0.1
            orgnr = 0.1
            skolekom = 0.05
            fagkode = 0.0
            stp = 3.0
            skr = 93.0
            mun = 96.0
            termin1 = 15.0
            termin2 = 99.93
            kar_annen = 99.99
