[paths]

[paths.daplalab_mounted]

produkt = "/buckets/produkt/nudb-data/"
katalog = "/buckets/produkt/nudb-data/konfigurasjon/kat/"
shared_root_external = "/buckets/shared/"
shared_root_internal = "/buckets/delt-utdanning/"
shared_utdanning_external = "/buckets/shared/utd-nudb/utdanning/nudb-data"
shared_utdanning_internal = "/buckets/delt-utdanning/nudb-data/"


[paths.on_prem]
shared_utdanning_external = "/ssb/stamme03/nudbut/nyeste/"

[paths.url_gcs]
shared_utdanning_external = "ssb-utd-nudb-data-delt-utdanning-prod/nudb-data/"
