[paths]
shared_root = "/buckets/shared"

[paths.local_daplalab]
utdanning_shared_local = "/buckets/delt-utdanning/nudb-data"
produkt = "/buckets/produkt/nudb-data/"
katalog = "/buckets/produkt/nudb-data/konfigurasjon/kat/"
delt_utdanning = "/buckets/shared/utd-nudb/utdanning/"

[paths.on_prem]
delt_utdanning = "/ssb/stamme03/nudbut/nyeste"

[paths.url_gcs]
delt_utdanning = "ssb-utd-nudb-data-delt-utdanning-prod/nudb-data"
