[variables]



###################
# MICRODATA TEMPORAL FRAGMENTS
###################

	[variables.gyldig_fra_dato]
		unit = "tid"
		dtype = "DATETIME"
		description_short = "Gyldig fra dato for microdata event"

	[variables.gyltid_til_dato]
		unit = "tid"
		dtype = "DATETIME"
		description_short = "Gyldig til dato for microdata event"


###################
# IGANG #
###################

	[variables.IGANG_utd_skolekom]
		unit = "skole"
		dtype = "STRING"
		description_short = "utd_skolekom from IGANG. Also in AVSLUTTA and IGANG"
		derived_from = ["utd_skolekom"]
		derived_uses_datasets = ["igang"]

###################
# AVSLUTTA #
###################

	[variables.AVSL_utd_skolekom]
		unit = "skole"
		dtype = "STRING"
		description_short = "utd_skolekom from AVSLUTTA. Also in IGANG and EKSAMEN"
		derived_from = ["utd_skolekom"]
		derived_uses_datasets = ["avslutta"]

###################
# EKSAMEN #
###################

	[variables.EKS_utd_skolekom]
		unit = "skole"
		dtype = "STRING"
		description_short = "utd_skolekom from EKSAMEN. Also in IGANG and AVSLUTTA"
		derived_from = ["utd_skolekom"]
		derived_uses_datasets = ["eksamen"]


#########################
# GRUNNSKOLE KARAKTERER #
#########################

	[variables.grsk_utd_skolekom]
		unit = "gro"
		dtype = "STRING"
		description_short = "Skolekom from kargrs"
		derived_from = ["utd_skolekom"]
		derived_uses_datasets = ["kargrs"]

	[variables.grsk_gro_fagkode_vigo]
		unit = "gro"
		dtype = "STRING"
		description_short = "Vigo fagkode from kargrs"
		derived_from = ["gro_fagkode_vigo"]
		derived_uses_datasets = ["kargrs"]


	[variables.grsk_gro_karakter_termin1]
		unit = "gro"
		dtype = "STRING"
		description_short = "karakter termi1 from kargrs"
		derived_from = ["gro_karakter_termin1"]
		derived_uses_datasets = ["kargrs"]

	[variables.grsk_gro_karakter_termin2]
		unit = "gro"
		dtype = "STRING"
		description_short = "karakter termin2 from kargrs"
		derived_from = ["gro_karakter_termin2"]
		derived_uses_datasets = ["kargrs"]

	[variables.grsk_gro_karakter_standpunkt]
		unit = "gro"
		dtype = "STRING"
		description_short = "karakter standpunkt from kargrs"
		derived_from = ["gro_karakter_standpunkt"]
		derived_uses_datasets = ["kargrs"]

	[variables.grsk_gro_karakter_skriftlig]
		unit = "gro"
		dtype = "STRING"
		description_short = "karakter skriftlig from kargrs"
		derived_from = ["gro_karakter_skriftlig"]
		derived_uses_datasets = ["kargrs"]

	[variables.grsk_gro_karakter_muntlig]
		unit = "gro"
		dtype = "STRING"
		description_short = "karakter muntlig from kargrs"
		derived_from = ["gro_karakter_muntlig"]
		derived_uses_datasets = ["kargrs"]

#########################
# VIDEREGAAENDE KARAKTERER #
#########################

	#########################
# VIDEREGAAENDE KARAKTERER #
#########################

	[variables.vg_fagkode]
		unit = "vg"
		dtype = "STRING"
		description_short = "Fagkode from videregaaende karakterer"
		derived_from = ["fagkode"]
		derived_uses_datasets = ["produkt"]

	[variables.vg_videregaaendepoeng]
		unit = "vg"
		dtype = "STRING"
		description_short = "Videregaendepoeng from videregaaende karakterer"
		derived_from = ["videregaendepoeng"]
		derived_uses_datasets = ["produkt"]

	[variables.vg_karakter_muntlig]
		unit = "vg"
		dtype = "STRING"
		description_short = "Muntlig karakter from videregaaende karakterer"
		derived_from = ["mun"]
		derived_uses_datasets = ["produkt"]

	[variables.vg_karakter_skriftlig]
		unit = "vg"
		dtype = "STRING"
		description_short = "Skriftlig karakter from videregaaende karakterer"
		derived_from = ["skr"]
		derived_uses_datasets = ["produkt"]

	[variables.vg_karakter_standpunkt]
		unit = "vg"
		dtype = "STRING"
		description_short = "Standpunkt karakter from videregaaende karakterer"
		derived_from = ["stp"]
		derived_uses_datasets = ["produkt"]


###################
# PERSONVARIABLER & SEMESTERS #
###################

	[variables.sosbak]
		unit = "pers"
		dtype = "STRING"
		description_short = "Foreldrenes høyeste utdanningsnivå ved personens alder 16"
		derived_from = ["utd_foreldres_utdnivaa_16aar_nus2000"]

	[variables.nus2000_far_16]
		unit = "pers"
		dtype = "STRING"
		description_short = "Fars høyeste utdanningsnivå ved personens alder 16"
		derived_from = ["utd_hoeyeste_nus2000"]

	[variables.nus2000_mor_16]
		unit = "pers"
		dtype = "STRING"
		description_short = "Mors høyeste utdanningsnivå ved personens alder 16"
		derived_from = ["utd_hoeyeste_nus2000"]

	[variables.komm_16]
		unit = "kommune"
		dtype = "STRING"
		description_short = "Bokommune ved fylte 16 år"
		derived_from = ["pers_bokommune_16aar"]

	[variables.aar_forste_fullf_gs]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte grunnskoleutdanning"
		derived_from = ["gr_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vs]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående utdanning"
		derived_from = ["vg_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vs_lov]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående utdanning (lovlig)"
		derived_from = ["vg_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vsa]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående studiespesialiserende utdanning"
		derived_from = ["vg_studiespess_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vsa_lov]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående studiespesialiserende utdanning (lovlig)"
		derived_from = ["vg_studiespess_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vsy]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående yrkesfaglige utdanning"
		derived_from = ["vg_yrkesfag_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_vsy_lov]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte videregående yrkesfaglige utdanning (lovlig)"
		derived_from = ["vg_yrkesfag_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_hoy]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte høyskolekandidatutdanning"
		derived_from = ["uh_hoeyskolekandidat_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_bach]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte bachelorutdanning"
		derived_from = ["uh_bachelor_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_hov]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte hovedfag/masterutdanning"
		derived_from = ["uh_master_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_cmg]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte profesjonsutdanning/masterutdanning"
		derived_from = ["uh_master_foerste_fullfoert_dato"]

	[variables.aar_forste_fullf_dok]
		unit = "tid"
		dtype = "STRING"
		description_short = "År for første fullførte doktorgradutdanning"
		derived_from = ["uh_doktorgrad_foerste_fullfoert_dato"]

	[variables.semester_fff_vs]
		unit = "tid"
		dtype = "INTEGER"
		description_short = "Kalendersemestre brukt på videregående"
		derived_from = ["semester_fff_vs"]

	[variables.semester_tot_fff_vs]
		unit = "tid"
		dtype = "INTEGER"
		description_short = "Aktive registrerte semestre på videregående"
		derived_from = ["semester_tot_fff_vs"]


#########################
# FAGVURDERING (LONG FORMAT) #
#########################

	[variables.fagvurdering_grsk_fagkode]
		unit = "fag"
		dtype = "STRING"
		description_short = "Fagkode for grunnskolekarakter"
		derived_from = ["gro_fagkode_vigo"]

	[variables.fagvurdering_grsk_karakter_standpunkt]
		unit = "karakter"
		dtype = "STRING"
		description_short = "Standpunktkarakter for grunnskole"
		derived_from = ["gro_karakter_standpunkt"]

	[variables.fagvurdering_grsk_karakter_skriftlig]
		unit = "karakter"
		dtype = "STRING"
		description_short = "Skriftlig karakter for grunnskole"
		derived_from = ["gro_karakter_skriftlig"]

	[variables.fagvurdering_grsk_karakter_muntlig]
		unit = "karakter"
		dtype = "STRING"
		description_short = "Muntlig karakter for grunnskole"
		derived_from = ["gro_karakter_muntlig"]

	[variables.fagvurdering_grsk_skole]
		unit = "skole"
		dtype = "STRING"
		description_short = "Skole for grunnskolekarakter"
		derived_from = ["utd_orgnr"]

	[variables.fagvurdering_vgs_fagkode]
		unit = "fag"
		dtype = "STRING"
		description_short = "Fagkode for videregående karakter"
		derived_from = ["fagkode"]

	[variables.fagvurdering_vgs_karakter]
		unit = "karakter"
		dtype = "STRING"
		description_short = "Karakter for videregående skole (stp, skr, mun)"
		derived_from = ["stp"]

	[variables.fagvurdering_vgs_vurderingsform]
		unit = "pers"
		dtype = "STRING"
		description_short = "Vurderingsform for videregående karakter"
		derived_from = ["stp"]

	[variables.fagvurdering_vgs_skole]
		unit = "skole"
		dtype = "STRING"
		description_short = "Skole for videregående karakter"
		derived_from = ["orgnrbed"]
